force-app/main/default/objects/Author_Reading__c/Author_Reading__c.object-meta.xml
<CustomObject>
    <description>An event where the author reads selected chapters from a new book which the attendees have the option of buying.</description>
    <label>Author Reading</label>
    <nameField>
        <label>Reading Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Author Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Reading__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The book that the author will be reading from.</description>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Author Readings</relationshipLabel>
    <relationshipName>Author_Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Author_Reading__c/fields/Ends__c.field-meta.xml
<CustomField>
    <fullName>Ends__c</fullName>
    <label>Ends</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Author_Reading__c/fields/Starts__c.field-meta.xml
<CustomField>
    <fullName>Starts__c</fullName>
    <label>Starts</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Author_Reading__c/fields/Virtual__c.field-meta.xml
<CustomField>
    <fullName>Virtual__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this is a virtual event.</description>
    <label>Virtual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>A book that is in the store inventory.</description>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>The book author.</description>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Published_Date__c.field-meta.xml
<CustomField>
    <fullName>Published_Date__c</fullName>
    <description>The date that the book was published</description>
    <label>Published Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The publisher of the book.</description>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AuthorService.cls
public with sharing class AuthorService implements AuthorServiceIF {
    @TestVisible
    private BookStoreDAOIF storeDAO;

    public AuthorService() {
        storeDAO=new BookStoreDAO();    
    }

    public void publishBooks(Author__c author, List<Book__c> books) {
        if (null==author)
        {
            throw new BookStoreException('Cannot publish books without specifying author');
        }

        if (null==books)
        {
            throw new BookStoreException('Cannot publish null collection of books');
        }

        List<Book__c> booksToUpdate=new List<Book__c>();

        for (Book__c book : books)
        {
            if (null!=book) {
                book.Published_Date__c=System.today();
                book.Publisher__c=author.Publisher__c;
                booksToUpdate.add(book);
            }
        }

        storeDAO.updateBooks(booksToUpdate);
    }

    public void scheduleReading(Book__c book, DateTime starts, DateTime ends,
                                Boolean virtualReading) {
        if (null==book)
        {
            throw new BookStoreException('A reading must specify a book');
        }

        if (null==starts)
        {
            throw new BookStoreException('Must specify reading start date and time');
        }

        if (null==ends)
        {
            throw new BookStoreException('Must specify reading end date and time');
        }

        if (null==virtualReading)
        {
            virtualReading=false;
        }

        Author__c author=storeDAO.getAuthor(book.Author__c);

        Author_Reading__c reading=new Author_Reading__c(Book__c=book.Id,
                                                        Starts__c=starts,
                                                        Ends__c=ends,
                                                        Virtual__c=virtualReading);
        storeDAO.createAuthorReading(reading);

        createSendInvitesTask('Reading', ends.date().addDays(-1), reading.Id);

        if (virtualReading) {
            createVideoConference(reading, author, book, starts, ends);
        }
    }

    private Task createSendInvitesTask(String eventType, Date dueDate, Id whatId) {
        Task sendInvites = new Task();
        sendInvites.Subject = 'Send Invitations to ' + eventType;
        sendInvites.Status = 'Not Started';
        sendInvites.Priority = 'Normal';
        sendInvites.ActivityDate = dueDate;
        sendInvites.WhatId = whatId;
        sendInvites.OwnerId = UserInfo.getUserId();

        storeDAO.createTask(sendInvites);

        return sendInvites;
    }

    private Event createVideoConference(Author_Reading__c reading, Author__c author, Book__c book,
                                       DateTime starts, DateTime ends) {
        Event videoConference = new Event();
        videoConference.Subject = 'Reading of ' + book.Name + ' by ' + author.Name;
        videoConference.StartDateTime = starts;
        videoConference.EndDateTime = ends;
        videoConference.Location = 'Online';
        videoConference.WhatId = reading.Id;
        videoConference.OwnerId = UserInfo.getUserId();

        storeDAO.createEvent(videoConference);

        return videoConference;
    }
}