force-app/main/default/objects/Author_Reading__c/Author_Reading__c.object-meta.xml
<CustomObject>
    <description>An event where the author reads selected chapters from a new book which the attendees have the option of buying.</description>
    <label>Author Reading</label>
    <nameField>
        <label>Reading Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Author Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Reading__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The book that the author will be reading from.</description>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Author Readings</relationshipLabel>
    <relationshipName>Author_Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>A book that is in the store inventory.</description>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>The book author.</description>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BookStoreDAOUpdateBooksSpy.cls
@IsTest
public class BookStoreDAOUpdateBooksSpy implements BookStoreDAOIF {

    public List<UpdateBooksSpyRecord> updateBooksHistory=new List<UpdateBooksSpyRecord>();

    public class UpdateBooksSpyRecord {
        public List<Book__c> books;

        public UpdateBooksSpyRecord(List<Book__c> books) {
            this.books = books;
        }
    }

    public BookStoreDAOUpdateBooksSpy() {}

    public void createBooks(List<Book__c> books) {}

    public void updateBooks(List<Book__c> books) {
        updateBooksHistory.add(new UpdateBooksSpyRecord(books));
    }

    public void createAuthor(Author__c author) {}

    public void createAuthorReading(Author_Reading__c reading) {}

    public void createTask(Task task){}

    public void createEvent(Event event){}

    public Author__c getAuthor(Id authorId) {
        return null;
    }

    public List<Book__c> getBooksForAuthorName(String authorName) {
        return null;
    }
}