force-app/main/default/objects/Author__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>Rating for the author - 1 (worst) to 5 (best)</description>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>A book that is in the store inventory.</description>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>The book author.</description>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>The literary genre of the book.</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book__c/fields/Published_Date__c.field-meta.xml
<CustomField>
    <fullName>Published_Date__c</fullName>
    <description>The date that the book was published</description>
    <label>Published Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The publisher of the book.</description>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fantasy</fullName>
    </customValue>
    <customValue>
        <fullName>Science fiction</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Mystery</fullName>
    </customValue>
    <customValue>
        <fullName>Detective</fullName>
    </customValue>
    <customValue>
        <fullName>Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Self-help</fullName>
    </customValue>
    <customValue>
        <fullName>Biography</fullName>
    </customValue>
    <customValue>
        <fullName>Thriller</fullName>
        <isActive>false</isActive>
        <label>Thriller</label>
    </customValue>
    <customValue>
        <fullName>Romance</fullName>
        <isActive>false</isActive>
        <label>Romance</label>
    </customValue>
    <customValue>
        <fullName>Western</fullName>
        <isActive>false</isActive>
        <label>Western</label>
    </customValue>
    <description>A literary genre.</description>
    <masterLabel>Genre</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FullBookStoreTestDataFactory.cls
@IsTest
public class FullBookStoreTestDataFactory {
    public static Author__c BuildAuthor(String name, Id publisherId) {
        return BuildAuthor(name, publisherId, '3');
    }

    public static Author__c BuildAuthor(String name, Id publisherId, String rating ) {
        Author__c author=new Author__c(Name=name,
                                       Publisher__c=publisherId,
                                       Rating__c=rating);

        return author;
    }

    public static Author__c CreateAuthor(String name, Id publisherId) {
        return CreateAuthor(name, publisherId, '3');
    }

    public static Author__c CreateAuthor(String name, Id publisherId, String rating) {
        Author__c author=BuildAuthor(name, publisherId, rating);
        insert author;

        return author;
    }

    public static Publisher__c BuildPublisher(String name) {
        Publisher__c publisher=new Publisher__c(Name=name);

        return publisher;
    }

    public static Publisher__c CreatePublisher(String name) {
        Publisher__c publisher=BuildPublisher(name);
        insert publisher;

        return publisher;
    }

    public static Book__c BuildBook(String name, Id authorId,
                                    String genre, Integer pageCount) {

        return BuildBook(name, authorId, genre, pageCount, null);
    }

    public static Book__c BuildBook(String name, Id authorId,
                                    String genre, Integer pageCount,
                                    Id publisherId) {
        return BuildBook(name, authorId, genre, pageCount, publisherId, null);
    }

    public static Book__c BuildBook(String name, Id authorId,
                                    String genre, Integer pageCount,
                                    Id publisherId, Date publishedDate) {
        Book__c book=new Book__c(Name=name,
                                 Author__c=authorId,
                                 Genre__c=genre,
                                 Pages__c=pageCount,
                                 Published_Date__c=publishedDate,
                                 Publisher__c=publisherId);

        return book;
    }

    public static Book__c CreateBook(String name, Id authorId,
                                     String genre, Integer pageCount) {
        return CreateBook(name, authorId, genre, pageCount, null);
    }

    public static Book__c CreateBook(String name, Id authorId,
                                    String genre, Integer pageCount,
                                    Id publisherId) {
        return CreateBook(name, authorId, genre, pageCount, publisherId, null);
    }

    public static Book__c CreateBook(String name, Id authorId,
                                    String genre, Integer pageCount,
                                    Id publisherId, Date publishedDate) {
        Book__c book=BuildBook(name, authorId, genre, pageCount, publisherId, publishedDate);
        insert book;                                        

        return book;
    }
}